### ISSUE TITLE
ModuleNotFoundError: No module named 'histdata'

### ISSUE THREAD

**Issue by mg64ve** [5ymph0en1x/Heptet#1]
Hello, nice work, thanks for sharing.
I am trying to follow your instructions and run:

```
python formater_piphist.py
```

but I am getting the following error:
```
Traceback (most recent call last):
  File "formater_piphist.py", line 4, in <module>
    from histdata import download_hist_data as dl
ModuleNotFoundError: No module named 'histdata'
```
where is this module supposed to be?
is it correct to run this code from EXAMPLES/Symphoenix directory?

**Comment by mg64ve** [comment]
sorry, this was an easy one, I solved just doing:

```
pip install histdata
```

**Comment by 5ymph0en1x** [comment]
Hello mg64ve !
You can avoid this kind of errors by running: 
`pip install -r requirements.txt`
Be sure to move the scripts from the folder 'EXAMPLES/Symphoenix' to the root before running them ! You may need to create some folders to host the files you will download through 'formater_piphist.py'.
Best regards

**Comment by mg64ve** [comment]
ok thanks @5ymph0en1x 
I have tried USDCAD/GBPUSD pair but it does not open trades, p-values seems to be always very high.
I am now trying with another pair but I am getting certificate expired when getting data from histdata.
It seems their certificated is expired. I wrote them to inform.

**Comment by 5ymph0en1x** [comment]
@mg64ve 
How long did you wait before stopping your first test ?
It can take up to a few hours before seeing some action...

**Comment by mg64ve** [comment]
@5ymph0en1x I haven't stopped yet, it is running since Monday morning, no trade.
p-value is always around 0.8-0.9
Do you think something not working properly maybe for a mistake in the process?

**Comment by mg64ve** [comment]
@5ymph0en1x it seems now histdata is working fine.
One more question, training at beginning prints a lot of these messages:

```
/opt/conda/lib/python3.7/site-packages/statsmodels/regression/linear_model.py:867: RuntimeWarning: divide by zero encountered in log
  llf = -nobs2*np.log(2*np.pi) - nobs2*np.log(ssr / nobs) - nobs2
/opt/conda/lib/python3.7/site-packages/statsmodels/base/model.py:1294: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/conda/lib/python3.7/site-packages/statsmodels/tsa/stattools.py:1432: CollinearityWarning: y0 and y1 are (almost) perfectly colinear.Cointegration test is not reliable in this case.
  CollinearityWarning)
/opt/conda/lib/python3.7/site-packages/statsmodels/tsa/stattools.py:1432: CollinearityWarning: y0 and y1 are (almost) perfectly colinear.Cointegration test is not reliable in this case.
  CollinearityWarning)
/opt/conda/lib/python3.7/site-packages/statsmodels/regression/linear_model.py:867: RuntimeWarning: divide by zero encountered in log
  llf = -nobs2*np.log(2*np.pi) - nobs2*np.log(ssr / nobs) - nobs2
/opt/conda/lib/python3.7/site-packages/statsmodels/base/model.py:1294: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/conda/lib/python3.7/site-packages/statsmodels/regression/linear_model.py:867: RuntimeWarning: divide by zero encountered in log
  llf = -nobs2*np.log(2*np.pi) - nobs2*np.log(ssr / nobs) - nobs2
/opt/conda/lib/python3.7/site-packages/statsmodels/base/model.py:1294: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/conda/lib/python3.7/site-packages/statsmodels/base/model.py:1294: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/conda/lib/python3.7/site-packages/statsmodels/regression/linear_model.py:867: RuntimeWarning: divide by zero encountered in log
  llf = -nobs2*np.log(2*np.pi) - nobs2*np.log(ssr / nobs) - nobs2
/opt/conda/lib/python3.7/site-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: divide by zero encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/opt/conda/lib/python3.7/site-packages/statsmodels/regression/linear_model.py:867: RuntimeWarning: divide by zero encountered in log
```

it seems it is statsmodel. Do you also get these messages?
Are they relevant?

**Comment by 5ymph0en1x** [comment]
@mg64ve 
I also get these messages but it doesn't prevent the algo from running fine.
I noticed that p-value tends to be higher at the beginning of the week...
Best regards
